apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pasu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ozfq-tenant/rhtap-demo-app/hacbs-test-project-pasu@sha256:dcc6d215d40f0561c6d7a0eb4851af4a6016b5a057e7937249bc82dfcc242235
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
