apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-pasu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-pasu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-pasu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-pasu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-pasu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ozfq-tenant/rhtap-demo-app/hacbs-test-project-pasu@sha256:2b867044b42a7c9f694624e5b8265d734c6d86558fca280b817077889db9cce1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
